Public Module BoilerplateState
    Public Const MainMenu = "MainMenu"
    Public Const Splash = "Splash"
    Public Const ConfirmQuit = "ConfirmQuit"
    Public Const Options = "Options"
    Public Const About = "About"
    Public Const Embark = "Embark"
    Public Const Load = "Load"
    Public Const WindowSize = "WindowSize"
    Public Const Volume = "Volume"
    Public Const Neutral = "Neutral"
    Public Const GameMenu = "GameMenu"
    Public Const Save = "Save"
    Public Const Abandon = "Abandon"
End Module
